project_id: '862468'
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: src/lib/i18n/resources/**/*.json
    translation: src/lib/i18n/resources/**/%locale%/%original_file_name%
    dest: TrackGeek/%original_file_name%
bundles:
  - 1
